steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.api:$TAG_NAME', '--file', './Dockerfile.gcp', '.' ]

# See:: https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.api:$TAG_NAME']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
  'run', 'deploy', 'fhirlabs-api', 
  '--region', 'us-west1', 
  '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.api:$TAG_NAME', 
  '--max-instances', '1', 
  '--min-instances', '1',
  '--concurrency', '8', 
  '--set-env-vars', 'GCLOUD_PROJECT=true,BUCKET=fhirlabs-r4-bucket',
  '--execution-environment', 'gen2',
  '--cpu', '2000m',
  '--memory', '2048Mi'
  ]

images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fhirlabs.api:$TAG_NAME'