// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigil.Common.Data;

#nullable disable

namespace Sigil.Common.Migrations
{
    [DbContext(typeof(SigilDbContext))]
    [Migration("20260412194401_WidenStoreProviderHint")]
    partial class WidenStoreProviderHint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sigil")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sigil.Common.Data.Entities.CaCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorityInfoAccessUri")
                        .HasColumnType("text");

                    b.Property<byte>("CertSecurityLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrlDistributionPoint")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("EncryptedPfxBytes")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("PfxPassword")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StoreProviderHint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("X509CertificatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.ToTable("CaCertificates", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CertificateRevocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CrlId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RevocationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevocationReason")
                        .HasColumnType("integer");

                    b.Property<string>("RevokedCertSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RevokedCertThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CrlId");

                    b.ToTable("CertificateRevocations", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CertificateTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiaUrlTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CdpUrlTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte>("CertificateType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EcdsaCurve")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExtendedKeyUsageOids")
                        .HasColumnType("text");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IncludeAia")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeCdp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBasicConstraintsCa")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBasicConstraintsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExtendedKeyUsageCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKeyUsageCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer");

                    b.Property<int>("KeyUsageFlags")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PathLengthConstraint")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectAltNameTypes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CertificateTemplates", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Communities", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Crl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CaCertificateId")
                        .HasColumnType("integer");

                    b.Property<long>("CrlNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NextUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RawBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ThisUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaCertificateId");

                    b.ToTable("Crls", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.IssuedCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("EncryptedPfxBytes")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<int>("IssuingCaCertificateId")
                        .HasColumnType("integer");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PfxPassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SubjectAltNames")
                        .HasColumnType("text");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("X509CertificatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssuingCaCertificateId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.ToTable("IssuedCertificates", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("JobType")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetCertificateId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NextRunAt");

                    b.ToTable("Jobs", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.JobExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobExecutions", "sigil");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CaCertificate", b =>
                {
                    b.HasOne("Sigil.Common.Data.Entities.Community", "Community")
                        .WithMany("CaCertificates")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigil.Common.Data.Entities.CaCertificate", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Community");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CertificateRevocation", b =>
                {
                    b.HasOne("Sigil.Common.Data.Entities.Crl", "Crl")
                        .WithMany("Revocations")
                        .HasForeignKey("CrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crl");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Crl", b =>
                {
                    b.HasOne("Sigil.Common.Data.Entities.CaCertificate", "CaCertificate")
                        .WithMany("Crls")
                        .HasForeignKey("CaCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaCertificate");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.IssuedCertificate", b =>
                {
                    b.HasOne("Sigil.Common.Data.Entities.CaCertificate", "IssuingCaCertificate")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("IssuingCaCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sigil.Common.Data.Entities.CertificateTemplate", "Template")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IssuingCaCertificate");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.JobExecution", b =>
                {
                    b.HasOne("Sigil.Common.Data.Entities.Job", "Job")
                        .WithMany("Executions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CaCertificate", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Crls");

                    b.Navigation("IssuedCertificates");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.CertificateTemplate", b =>
                {
                    b.Navigation("IssuedCertificates");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Community", b =>
                {
                    b.Navigation("CaCertificates");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Crl", b =>
                {
                    b.Navigation("Revocations");
                });

            modelBuilder.Entity("Sigil.Common.Data.Entities.Job", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
